services:
  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  api:
    image: ghcr.io/veqox/kubernetes-demo:latest
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/demo
    ports:
      - "8080:8080"