services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data