services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data