name: Build and Deploy Dockerfiles
run-name: Build and Deploy Dockerfile
on: push
jobs:
    build-images:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@4
            - name: Setup java
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '21'
                  cache: 'maven'
            - name: Build and push docker image
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                GITHUB_ACTOR: ${{ github.actor }}
                GITHUB_REPOSITORY: ${{ github.repository }}
              run: build.sh
